language: python

sudo: "required"

addons:
  firefox: "latest-nightly"

env:
  global:
    - DISPLAY=:99.0
matrix:
  include:
    - python: 2.7
      env: TOXENV=flake8
    - python: 2.7
      env: TOXENV=py27
    - python: 3.5
      env: TOXENV=flake8
    - python: 3.5
      env: TOXENV=py35

before_install:
  - wget -O geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
  - gunzip -c geckodriver.tar.gz | tar xopf -
  - chmod +x geckodriver && sudo mv geckodriver /usr/local/bin
  - firefox --version
  - geckodriver --version

install:
  pip install tox-travis

notifications:
  webhooks:
    urls:
      - "https://silne30-foxpuppet.getbadges.io/api/app/webhook/b71ddba7-6feb-412c-8728-3efef552d02b"
    on_start: "change"

before_script:
  - sh -e /etc/init.d/xvfb start

script:
  - tox