language: python

sudo: "required"

python:
    - "2.7"
    - "3.5"

env:
  global:
    - DISPLAY=:99.0

before_install:
  - pip install mozdownload mozinstall
  - mozdownload --type daily --branch mozilla-central --destination firefox.tar.bz2
  - mozinstall firefox.tar.bz2
  - sudo ln -sf $PWD/firefox/firefox /usr/local/bin/firefox
  - wget -O geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.0-linux64.tar.gz
  - gunzip -c geckodriver.tar.gz | tar xopf -
  - chmod +x geckodriver && sudo mv geckodriver /usr/local/bin
  - firefox --version
  - geckodriver --version

install:
  pip install tox-travis

notifications:
  webhooks:
    urls:
      - "https://silne30-foxpuppet.getbadges.io/api/app/webhook/b71ddba7-6feb-412c-8728-3efef552d02b"
    on_start: "change"

before_script:
  - sh -e /etc/init.d/xvfb start

script:
  - tox-travis